#!/usr/bin/env bash
# build-context-graph.sh
# Builds or updates the graph index in .context/overview.md
# - Scans file content for @mentions and markdown links to other .context files
# - Uses directory structure to infer relationships
# - Merges into existing overview.md, preserving hand-authored sections
# - Outputs both a Mermaid diagram and a dependency list

set -euo pipefail

# ─── Config ────────────────────────────────────────────────────────────────────
CONTEXT_DIR="${1:-.context}"
OVERVIEW="$CONTEXT_DIR/overview.md"
GRAPH_START="<!-- GRAPH:START -->"
GRAPH_END="<!-- GRAPH:END -->"

# ─── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "▸ $*"; }
warn() { echo "⚠ $*" >&2; }

# Resolve a path relative to a source file, back to a .context-relative path
resolve_link() {
  local source_file="$1"   # relative to CONTEXT_DIR, e.g. standards/code-style.md
  local raw_link="$2"      # as it appears in the file, e.g. ../domains/glossary.md

  local source_dir
  source_dir="$(dirname "$source_file")"

  # Normalise: strip leading ./
  raw_link="${raw_link#./}"

  # If it starts with ../ or is a plain name, resolve relative to source_dir
  local resolved
  resolved="$(cd "$CONTEXT_DIR/$source_dir" 2>/dev/null && realpath -m --relative-to="$CONTEXT_DIR" "$raw_link" 2>/dev/null || true)"

  # Must exist inside CONTEXT_DIR and be a .md file
  if [[ -n "$resolved" && -f "$CONTEXT_DIR/$resolved" && "$resolved" == *.md ]]; then
    echo "$resolved"
  fi
}

# ─── 1. Collect all markdown files ─────────────────────────────────────────────
log "Scanning $CONTEXT_DIR ..."

mapfile -t ALL_FILES < <(
  find "$CONTEXT_DIR" -name "*.md" -not -name "overview.md" \
    | sed "s|^$CONTEXT_DIR/||" \
    | sort
)

if [[ ${#ALL_FILES[@]} -eq 0 ]]; then
  warn "No markdown files found in $CONTEXT_DIR"
  exit 1
fi

log "Found ${#ALL_FILES[@]} context files"

# ─── 2. Build adjacency map ─────────────────────────────────────────────────────
# deps[file] = space-separated list of files it references
declare -A deps
for f in "${ALL_FILES[@]}"; do
  deps["$f"]=""
done

for f in "${ALL_FILES[@]}"; do
  full="$CONTEXT_DIR/$f"
  found_deps=()

  # 2a. Content scan — @mentions: @filename.md or @path/to/file.md
  while IFS= read -r mention; do
    mention="${mention#@}"
    resolved="$(resolve_link "$f" "$mention")"
    if [[ -n "$resolved" && "$resolved" != "$f" ]]; then
      found_deps+=("$resolved")
    fi
  done < <(grep -oP '@[\w./-]+\.md' "$full" 2>/dev/null || true)

  # 2b. Content scan — markdown links: [text](path.md)
  while IFS= read -r link; do
    resolved="$(resolve_link "$f" "$link")"
    if [[ -n "$resolved" && "$resolved" != "$f" ]]; then
      found_deps+=("$resolved")
    fi
  done < <(grep -oP '\]\([\w./_-]+\.md\)' "$full" 2>/dev/null \
            | grep -oP '[\w./_-]+\.md' || true)

  # 2c. Directory structure — files in the same subdirectory are siblings
  dir="$(dirname "$f")"
  if [[ "$dir" != "." ]]; then
    while IFS= read -r sibling; do
      sibling="${sibling#$CONTEXT_DIR/}"
      if [[ "$sibling" != "$f" ]]; then
        found_deps+=("$sibling")
      fi
    done < <(find "$CONTEXT_DIR/$dir" -maxdepth 1 -name "*.md" -not -name "overview.md" | sort)
  fi

  # Deduplicate
  if [[ ${#found_deps[@]} -gt 0 ]]; then
    mapfile -t unique_deps < <(printf '%s\n' "${found_deps[@]}" | sort -u)
    deps["$f"]="${unique_deps[*]}"
  fi
done

# ─── 3. Build task routing map ──────────────────────────────────────────────────
# Infer task keywords from directory names and file names
declare -A task_map

for f in "${ALL_FILES[@]}"; do
  dir="$(dirname "$f")"
  base="$(basename "$f" .md)"

  # Use directory as task category key
  local_key="$dir"
  [[ "$local_key" == "." ]] && local_key="general"

  if [[ -v task_map["$local_key"] ]]; then
    task_map["$local_key"]+=" $f"
  else
    task_map["$local_key"]="$f"
  fi
done

# ─── 4. Render graph sections ───────────────────────────────────────────────────
render_graph() {
  echo "$GRAPH_START"
  echo "<!-- Auto-generated by build-context-graph.sh — do not edit this block manually -->"
  echo ""

  # ── 4a. File index ──
  echo "## File Index"
  echo ""
  echo "| File | Directory | Description |"
  echo "|------|-----------|-------------|"
  for f in "${ALL_FILES[@]}"; do
    dir="$(dirname "$f")"
    [[ "$dir" == "." ]] && dir="root"
    # Pull first non-empty, non-heading line as description
    desc="$(grep -m1 -v '^#' "$CONTEXT_DIR/$f" 2>/dev/null \
            | grep -v '^\s*$' | head -1 | cut -c1-80 || true)"
    echo "| \`$f\` | \`$dir\` | ${desc:-—} |"
  done
  echo ""

  # ── 4b. Mermaid diagram ──
  echo "## Dependency Graph"
  echo ""
  echo '```mermaid'
  echo "graph TD"

  # Node labels (sanitise slashes for mermaid IDs)
  for f in "${ALL_FILES[@]}"; do
    id="${f//\//__}"
    id="${id//-/_}"
    id="${id//./_}"
    label="$(basename "$f" .md)"
    echo "  $id[\"$label\"]"
  done

  echo ""

  # Edges
  edge_count=0
  for f in "${ALL_FILES[@]}"; do
    if [[ -n "${deps[$f]}" ]]; then
      src_id="${f//\//__}"
      src_id="${src_id//-/_}"
      src_id="${src_id//./_}"
      for dep in ${deps[$f]}; do
        dep_id="${dep//\//__}"
        dep_id="${dep_id//-/_}"
        dep_id="${dep_id//./_}"
        echo "  $src_id --> $dep_id"
        (( edge_count++ )) || true
      done
    fi
  done

  [[ $edge_count -eq 0 ]] && echo "  %% No explicit links found — relationships inferred from directory structure only"

  echo '```'
  echo ""

  # ── 4c. Dependency list (for Claude to parse) ──
  echo "## Dependency List"
  echo ""
  for f in "${ALL_FILES[@]}"; do
    if [[ -n "${deps[$f]}" ]]; then
      dep_list="$(echo "${deps[$f]}" | tr ' ' '\n' | sed 's/^/`/' | sed 's/$/`/' | paste -sd ', ')"
      echo "- \`$f\` → [$dep_list]"
    else
      echo "- \`$f\` → [] <!-- leaf node -->"
    fi
  done
  echo ""

  # ── 4d. Task routing ──
  echo "## Task Routing"
  echo ""
  echo "<!-- Map task keywords to relevant context files for Claude to use when selecting context -->"
  echo ""
  for key in $(echo "${!task_map[@]}" | tr ' ' '\n' | sort); do
    files_list="$(echo "${task_map[$key]}" | tr ' ' '\n' | sed 's/^/`/' | sed 's/$/`/' | paste -sd ', ')"
    echo "- **$key** → [$files_list]"
  done
  echo ""

  echo "$GRAPH_END"
}

# ─── 5. Merge into overview.md ──────────────────────────────────────────────────
NEW_GRAPH="$(render_graph)"

if [[ ! -f "$OVERVIEW" ]]; then
  log "overview.md not found — creating fresh"
  cat > "$OVERVIEW" <<EOF
# Overview

> Auto-generated index for \`.context/\`. Hand-authored sections outside the graph block are preserved on rebuild.

$NEW_GRAPH
EOF
  log "Created $OVERVIEW"
  exit 0
fi

# Check if graph block exists
if grep -q "$GRAPH_START" "$OVERVIEW"; then
  log "Merging — updating graph block in existing overview.md"

  # Replace everything between GRAPH:START and GRAPH:END (inclusive)
  # Using awk for reliable multi-line replacement
  awk -v new_graph="$NEW_GRAPH" '
    /<!-- GRAPH:START -->/ { in_block=1; print new_graph; next }
    /<!-- GRAPH:END -->/   { in_block=0; next }
    !in_block              { print }
  ' "$OVERVIEW" > "$OVERVIEW.tmp" && mv "$OVERVIEW.tmp" "$OVERVIEW"

  log "Graph block updated — hand-authored content preserved"
else
  log "No graph block found — appending graph to existing overview.md"
  echo "" >> "$OVERVIEW"
  echo "$NEW_GRAPH" >> "$OVERVIEW"
  log "Graph appended to $OVERVIEW"
fi

# ─── 6. Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "✓ Graph built successfully"
echo "  Files indexed : ${#ALL_FILES[@]}"
edge_total=0
for f in "${ALL_FILES[@]}"; do
  [[ -n "${deps[$f]}" ]] && edge_total=$(( edge_total + $(echo "${deps[$f]}" | wc -w) )) || true
done
echo "  Edges found   : $edge_total"
echo "  Output        : $OVERVIEW"